### PR TITLE
Output tokens per deployment

### PR DESCRIPTION
**Pull request by hansonchun-quartech**
### Description

The max response token limit can be different for each deployment model. This PR allows the range selection for the max response of a specialization to adapt based on the deployment model selected for it. 

Also, while working on this ticket, I realized I had misinterpreted the token configs the first time around. Refer to this screenshot:

image

 `CompletionTokenLimit` should actually be the Context Window tokens, and `MaxResponseTokenLimit` should be the Max Output tokens. Previously, we were using `CompletionTokenLimit` for the Max Output tokens, which greatly limited the number of tokens we could have been using for the context. I've updated the helm configs accordingly - this update will give us way more tokens to use for memories and chat history.

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by sam0044** [comment]
So all the models we have right now deployed. They are able to use 16,384 tokens as output?

**Review by sam0044 — COMMENTED** [review]
I am seeing a bunch of lint errors in SpecializationManager and unsafe assignments in other files. 
Screenshot (161)

**Comment by hansonchun-quartech** [comment]
> So all the models we have deployed right now. They are able to use 16,384 tokens as output?

Here are the output tokens we can use for each model:
- gpt-4o - 16384,
- gpt-4 - 4096,
- gpt-4o-mini - 16384

**Comment by hansonchun-quartech** [comment]
> I am seeing a bunch of lint errors in SpecializationManager and unsafe assignments in other files. Screenshot (161)

You will need to recompile the frontend to make this go away. I changed the return type of `getAllChatCompletionDeploymentsAsync` from `string[]` to `IChatCompletionDeployment[]`

**Comment by sam0044** [comment]
I thought I did weird. Yeah they are gone now. I meant the models we are using are they updated versions? Because the old versions don't have the same tokens

**Comment by hansonchun-quartech** [comment]
> I thought I did weird. Yeah they are gone now. I meant the models we are using are they updated versions? Because the old versions don't have the same tokens

yeah we are using these model versions

gpt-4 - turbo-2024-04-09 - 4096
gpt-4o - 2024-08-06 - 16384
gpt-4o-mini - 2024-07-18 - 16384

**Review by sam0044 — APPROVED** [review]
LGTM!

**Pull request merged**
